#!/usr/bin/env python3
"""
Batch driver for mcrp_to_vox (fixed output-volume / production mode).

Builds one MC-GPU voxel phantom per MRCP model found in the phantoms/ directory,
all sharing the SAME fixed output volume (default 640x640x300 mm @ 0.3 mm).  For
every phantom the head tip is aligned to the top of the volume and the top 30 cm
of anatomy is captured — so newborns and adults come out at identical dimensions,
only the amount of body below the head differs.

The geometry (volume size, head-tip anchoring, XY centring, auto stretcher) is
handled by the binary; this script just enumerates phantoms, writes one .cfg per
phantom from the template (overriding phantom_name + a per-phantom output name),
and runs the binary.  The .in material list is copied verbatim from the template
for every phantom (geometry is the focus, not per-phantom material accuracy).

After each phantom is built it renders a central-sagittal POSITIONING-CHECK PNG
(phantom + stretcher with the CBCT beam overlaid) into positioning_checks/, using
the same renderer as expand_in_kv.py.  Use --no-checks to skip.

Prerequisite: each phantom must have its material map at
    data/mcgpu_mcrp_materials/<phantom>/MC-GPU_material_config.txt
(generated by mcrp_to_mcgpu_materials / run_all_mcgpu_materials.sh).  Phantoms
without one are skipped with a warning.

Examples
--------
  # write .cfg files only, don't run the (slow, ~4.5 GB each) voxelizations
  python3 batch_mcrp_to_vox.py --dry-run

  # build all phantoms
  python3 batch_mcrp_to_vox.py

  # only a couple of phantoms
  python3 batch_mcrp_to_vox.py --only MRCP-00F MRCP_AM
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_TEMPLATE = "params/mcrp_to_vox_template.cfg"
DEFAULT_BINARY = "build/mcrp_to_vox"
DEFAULT_PHANTOM_DIR = "phantoms"
DEFAULT_MATERIAL_DIR = "data/mcgpu_mcrp_materials"
DEFAULT_CFG_OUT_DIR = "params/generated_mcrp"
DEFAULT_PNG_DIR = "positioning_checks"
# Markers the binary prints for every .raw / .in it writes.
RAW_WRITTEN_MARKER = "Label phantom written to:"
IN_WRITTEN_MARKER = "MC-GPU .in file written:"

# Overridden per phantom; everything else comes from the template.
OVERRIDE_KEYS = ("phantom_name", "mcgpu_output_name", "output_dir")
PATH_KEYS = ("output_dir",)


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", s).strip("_")


def render_check(in_path, png_dir: Path, phantom: str, cache: dict):
    """Render one central-sagittal positioning-check PNG for a generated .in,
    reusing expand_in_kv.render_positioning_check (single source of truth).
    The linked .raw sits beside the .in.  Returns the PNG path, or None."""
    from expand_in_kv import parse_in_geometry, render_positioning_check
    in_path = Path(in_path)
    geom = parse_in_geometry(in_path)
    raw = in_path.parent / geom["raw_name"]
    if not raw.is_file():
        print(f"    [warn] positioning check: .raw not found: {raw}")
        return None
    png_dir.mkdir(parents=True, exist_ok=True)
    out_png = png_dir / f"{slug(phantom)}_{in_path.stem}.png"
    render_positioning_check(in_path, raw, out_png, geom, cache)
    return out_png


def discover_phantoms(phantom_dir: Path):
    """Unique phantom stems that have a .node file (one per MRCP model)."""
    stems = sorted({p.stem for p in phantom_dir.glob("*.node")})
    if not stems:
        sys.exit(f"No *.node phantoms found in {phantom_dir}")
    return stems


def has_material_map(material_dir: Path, phantom: str) -> bool:
    return (material_dir / phantom / "MC-GPU_material_config.txt").is_file()


def build_cfg(template_text: str, overrides: dict) -> str:
    lines = [template_text.rstrip(), "",
             "# ===== batch overrides (appended; last value wins) ====="]
    for k in OVERRIDE_KEYS:
        if k not in overrides:
            continue
        v = overrides[k]
        if k in PATH_KEYS:
            v = '"' + str(v) + '"'
        lines.append(f"{k} = {v}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--template", default=DEFAULT_TEMPLATE)
    ap.add_argument("--binary", default=DEFAULT_BINARY)
    ap.add_argument("--phantoms-dir", default=DEFAULT_PHANTOM_DIR)
    ap.add_argument("--material-dir", default=DEFAULT_MATERIAL_DIR)
    ap.add_argument("--cfg-out-dir", default=DEFAULT_CFG_OUT_DIR)
    ap.add_argument("--output-dir", default=None,
                    help="override output_dir for every phantom (e.g. a data "
                         "drive); default: whatever the template sets "
                         "(./output if unset)")
    ap.add_argument("--only", nargs="+", metavar="PHANTOM",
                    help="only these phantom names (e.g. MRCP-00F MRCP_AM)")
    ap.add_argument("--dry-run", action="store_true",
                    help="write .cfg files but do not launch the binary")
    ap.add_argument("--stop-on-error", action="store_true")
    ap.add_argument("--png-dir", default=DEFAULT_PNG_DIR,
                    help="output folder for positioning-check PNGs "
                         "(default: %(default)s)")
    ap.add_argument("--no-checks", action="store_true",
                    help="skip rendering positioning-check PNGs after each build")
    args = ap.parse_args()

    template_path = REPO_ROOT / args.template
    binary = (REPO_ROOT / args.binary).resolve()
    phantom_dir = REPO_ROOT / args.phantoms_dir
    material_dir = REPO_ROOT / args.material_dir
    cfg_dir = REPO_ROOT / args.cfg_out_dir

    if not template_path.is_file():
        sys.exit(f"Template not found: {template_path}")
    if not args.dry_run and not binary.is_file():
        sys.exit(f"Binary not found: {binary}  (build it first)")
    template_text = template_path.read_text()
    cfg_dir.mkdir(parents=True, exist_ok=True)

    all_phantoms = discover_phantoms(phantom_dir)
    phantoms = all_phantoms
    if args.only:
        wanted = set(args.only)
        phantoms = [p for p in all_phantoms if p in wanted]
        missing = wanted - set(all_phantoms)
        if missing:
            for m in sorted(missing):
                print(f"  [warn] requested phantom not found: {m}")
            print(f"  available phantoms in {phantom_dir}:")
            print("    " + "  ".join(all_phantoms))

    jobs = []  # (cfg_path, phantom)
    for ph in phantoms:
        if not has_material_map(material_dir, ph):
            print(f"  [skip] {ph}: no material map in {material_dir}/{ph}/ "
                  f"(run mcrp_to_mcgpu_materials first)")
            continue
        overrides = {
            "phantom_name": ph,
            "mcgpu_output_name": f"results/{ph}_",
        }
        if args.output_dir:
            overrides["output_dir"] = args.output_dir
        cfg_path = cfg_dir / f"{slug(ph)}.cfg"
        cfg_path.write_text(build_cfg(template_text, overrides))
        jobs.append((cfg_path, ph))

    print(f"Prepared {len(jobs)} job(s).  cfg files -> {cfg_dir}")
    if args.dry_run:
        for cfg_path, ph in jobs:
            print(f"  [dry-run] {ph}: {cfg_path}")
        return

    # Verify the positioning-check renderer is importable once, up front.
    do_checks = not args.no_checks
    if do_checks:
        try:
            import matplotlib  # noqa: F401
            from expand_in_kv import render_positioning_check  # noqa: F401
        except Exception as e:                                  # noqa: BLE001
            print(f"  [warn] positioning checks disabled (missing dependency): {e}")
            do_checks = False
    png_dir = REPO_ROOT / args.png_dir

    failures, raw_entries, made_pngs = [], [], []
    slice_cache = {}
    for n, (cfg_path, ph) in enumerate(jobs, 1):
        print(f"\n=== [{n}/{len(jobs)}] {ph} ===")
        print(f"    {binary} {cfg_path}")
        proc = subprocess.Popen([str(binary), str(cfg_path)], cwd=str(REPO_ROOT),
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                text=True, bufsize=1)
        in_paths = []
        for line in proc.stdout:
            sys.stdout.write(line)
            if RAW_WRITTEN_MARKER in line:
                raw_entries.append((ph, line.split(RAW_WRITTEN_MARKER, 1)[1].strip()))
            elif IN_WRITTEN_MARKER in line:
                s = line.split(IN_WRITTEN_MARKER, 1)[1].strip()
                in_paths.append(s.rsplit("(from", 1)[0].strip() if "(from" in s else s)
        rc = proc.wait()
        if rc != 0:
            print(f"    !! exit code {rc}")
            failures.append((ph, rc))
            if args.stop_on_error:
                break
            continue
        # positioning check(s) for this phantom's generated .in file(s)
        if do_checks:
            for ip in in_paths:
                try:
                    png = render_check(ip, png_dir, ph, slice_cache)
                    if png:
                        made_pngs.append(png)
                        print(f"    [check] {png}")
                except Exception as e:                          # noqa: BLE001
                    print(f"    [warn] positioning check failed for {ip}: {e}")

    log = cfg_dir / "exported_raw.txt"
    lines = ["# exported .raw files\t<phantom>\t<raw_path>"]
    lines += [f"{ph}\t{p}" for ph, p in raw_entries]
    log.write_text("\n".join(lines) + "\n")
    print(f"\nExported {len(raw_entries)} .raw file(s); list -> {log}")
    if do_checks:
        print(f"Positioning checks: {len(made_pngs)} PNG(s) -> {png_dir}")
    print(f"Done: {len(jobs) - len(failures)}/{len(jobs)} succeeded.")
    if failures:
        for ph, rc in failures:
            print(f"  FAILED ({rc}): {ph}")
        sys.exit(1)


if __name__ == "__main__":
    main()
