#!/usr/bin/env python3
"""
Batch driver for mcrp_to_vox's TIGHT-CROP DICOM EXPORT mode.

Exports one DICOM HU series per MRCP model found in the phantoms/ directory —
no MC-GPU output at all (no labels, no .raw/.txt/.in, no implant/crop/
stretcher overlay). Each phantom's output is sized to its own captured
anatomy (head tip down to vol_length_mm, clamped to its own extent if
shorter) plus a flat air margin on every side, instead of a large fixed
volume — so a newborn and an adult phantom get very different sizes, each
with minimal wasted air.

This DICOM is meant to be fed into dicom_to_mcgpu (as if it were a real
patient series) downstream, for placement into a final fixed MC-GPU volume,
stretcher overlay, and stretcher-position data augmentation — see
HANDOUT_mcrp_dicom_stretcher_augmentation.md for that plan. This script only
produces the DICOM; it does not call dicom_to_mcgpu.

Prerequisite: each phantom must have its material map at
    data/mcgpu_mcrp_materials/<phantom>/MC-GPU_material_config.txt
(generated by mcrp_to_mcgpu_materials / run_all_mcgpu_materials.sh).  Phantoms
without one are skipped with a warning.

Examples
--------
  # write .cfg files only, don't run the voxelizations
  python3 batch_mcrp_to_dicom.py --dry-run

  # export all phantoms
  python3 batch_mcrp_to_dicom.py

  # only a couple of phantoms
  python3 batch_mcrp_to_dicom.py --only MRCP-00F MRCP_AM

  # redirect every phantom's DICOM onto a different drive/folder
  python3 batch_mcrp_to_dicom.py --output-dir /mnt/f/Michele_diskF/mcrp_dicom_export
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_TEMPLATE = "params/mcrp_to_dicom_template.cfg"
DEFAULT_BINARY = "build/mcrp_to_vox"
DEFAULT_PHANTOM_DIR = "phantoms"
DEFAULT_MATERIAL_DIR = "data/mcgpu_mcrp_materials"
DEFAULT_CFG_OUT_DIR = "params/generated_mcrp_dicom"
DICOM_WRITTEN_MARKER = "DICOM export written to:"

# Overridden per phantom; everything else comes from the template.
OVERRIDE_KEYS = ("phantom_name", "output_dir")
PATH_KEYS = ("output_dir",)


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", s).strip("_")


def discover_phantoms(phantom_dir: Path):
    """Unique phantom stems that have a .node file (one per MRCP model)."""
    stems = sorted({p.stem for p in phantom_dir.glob("*.node")})
    if not stems:
        sys.exit(f"No *.node phantoms found in {phantom_dir}")
    return stems


def has_material_map(material_dir: Path, phantom: str) -> bool:
    return (material_dir / phantom / "MC-GPU_material_config.txt").is_file()


def build_cfg(template_text: str, overrides: dict) -> str:
    lines = [template_text.rstrip(), "",
             "# ===== batch overrides (appended; last value wins) ====="]
    for k in OVERRIDE_KEYS:
        if k not in overrides:
            continue
        v = overrides[k]
        if k in PATH_KEYS:
            v = '"' + str(v) + '"'
        lines.append(f"{k} = {v}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--template", default=DEFAULT_TEMPLATE)
    ap.add_argument("--binary", default=DEFAULT_BINARY)
    ap.add_argument("--phantoms-dir", default=DEFAULT_PHANTOM_DIR)
    ap.add_argument("--material-dir", default=DEFAULT_MATERIAL_DIR)
    ap.add_argument("--cfg-out-dir", default=DEFAULT_CFG_OUT_DIR)
    ap.add_argument("--output-dir", default=None,
                    help="override output_dir for every phantom (e.g. a data "
                         "drive); default: whatever the template sets")
    ap.add_argument("--only", nargs="+", metavar="PHANTOM",
                    help="only these phantom names (e.g. MRCP-00F MRCP_AM)")
    ap.add_argument("--dry-run", action="store_true",
                    help="write .cfg files but do not launch the binary")
    ap.add_argument("--stop-on-error", action="store_true")
    args = ap.parse_args()

    template_path = REPO_ROOT / args.template
    binary = (REPO_ROOT / args.binary).resolve()
    phantom_dir = REPO_ROOT / args.phantoms_dir
    material_dir = REPO_ROOT / args.material_dir
    cfg_dir = REPO_ROOT / args.cfg_out_dir

    if not template_path.is_file():
        sys.exit(f"Template not found: {template_path}")
    if not args.dry_run and not binary.is_file():
        sys.exit(f"Binary not found: {binary}  (build it first)")
    template_text = template_path.read_text()
    cfg_dir.mkdir(parents=True, exist_ok=True)

    all_phantoms = discover_phantoms(phantom_dir)
    phantoms = all_phantoms
    if args.only:
        wanted = set(args.only)
        phantoms = [p for p in all_phantoms if p in wanted]
        missing = wanted - set(all_phantoms)
        if missing:
            for m in sorted(missing):
                print(f"  [warn] requested phantom not found: {m}")
            print(f"  available phantoms in {phantom_dir}:")
            print("    " + "  ".join(all_phantoms))

    jobs = []  # (cfg_path, phantom)
    for ph in phantoms:
        if not has_material_map(material_dir, ph):
            print(f"  [skip] {ph}: no material map in {material_dir}/{ph}/ "
                  f"(run mcrp_to_mcgpu_materials first)")
            continue
        overrides = {"phantom_name": ph}
        if args.output_dir:
            overrides["output_dir"] = args.output_dir
        cfg_path = cfg_dir / f"{slug(ph)}.cfg"
        cfg_path.write_text(build_cfg(template_text, overrides))
        jobs.append((cfg_path, ph))

    print(f"Prepared {len(jobs)} job(s).  cfg files -> {cfg_dir}")
    if args.dry_run:
        for cfg_path, ph in jobs:
            print(f"  [dry-run] {ph}: {cfg_path}")
        return

    failures, dicom_entries = [], []
    for n, (cfg_path, ph) in enumerate(jobs, 1):
        print(f"\n=== [{n}/{len(jobs)}] {ph} ===")
        print(f"    {binary} {cfg_path}")
        proc = subprocess.Popen([str(binary), str(cfg_path)], cwd=str(REPO_ROOT),
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                text=True, bufsize=1)
        for line in proc.stdout:
            sys.stdout.write(line)
            if DICOM_WRITTEN_MARKER in line:
                dicom_entries.append((ph, line.split(DICOM_WRITTEN_MARKER, 1)[1].strip()))
        rc = proc.wait()
        if rc != 0:
            print(f"    !! exit code {rc}")
            failures.append((ph, rc))
            if args.stop_on_error:
                break

    log = cfg_dir / "exported_dicom.txt"
    lines = ["# exported DICOM series\t<phantom>\t<dicom_dir>"]
    lines += [f"{ph}\t{p}" for ph, p in dicom_entries]
    log.write_text("\n".join(lines) + "\n")
    print(f"\nExported {len(dicom_entries)} DICOM series; list -> {log}")
    print(f"Done: {len(jobs) - len(failures)}/{len(jobs)} succeeded.")
    if failures:
        for ph, rc in failures:
            print(f"  FAILED ({rc}): {ph}")
        sys.exit(1)


if __name__ == "__main__":
    main()
