/run/initialize
/vis/open
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/viewer/set/style surface
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/colour Radiator 0 1 0 0 .5
/vis/scene/endOfEventAction accumulate