#pragma once

// MCRPMaterialMap.hpp
//
// Parses the MC-GPU_material_config.txt generated by mcrp_to_mcgpu_materials
// and builds a sequential label mapping:
//
//   MRCP organ ID (0..14000+)  →  sequential uint8 index (0..N)
//
// Index 0 is always the external air background.
// Indices 1..N are assigned in ascending MRCP-ID order, matching the
// material files present in data/mcgpu_mcrp_materials/<phantomName>/.
//
// Usage:
//   MCRPMaterialMap map;
//   map.load("./data/mcgpu_mcrp_materials/MRCP-00F");
//   int seq = map.getSeqIndex(100);   // e.g. returns 1
//   map.writeMCGPUSectionFile("output_mcgpu_section.txt", "MRCP-00F");

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

class MCRPMaterialMap {
public:
    struct Entry {
        int    mrcp_id;
        int    seq_index;
        std::string basename;   // e.g. "icrp_Adrenal_left.mcgpu"
        double density;
    };

    // Load mapping from the config file in the given directory.
    // configDir should be e.g. "./data/mcgpu_mcrp_materials/MRCP-00F"
    void load(const std::string& configDir)
    {
        std::string configPath = configDir + "/MC-GPU_material_config.txt";
        std::ifstream file(configPath);
        if (!file.is_open())
            throw std::runtime_error("MCRPMaterialMap: cannot open " + configPath);

        entries_.clear();
        mrcp_to_seq_.clear();

        std::string line;
        while (std::getline(file, line)) {
            if (line.empty() || line[0] == '#') continue;

            // Expected format (possibly with absolute path prefix):
            //   material/<path>/icrp_NAME.mcgpu density=<val> voxelId=<id>
            double density = 0.0;
            int    mrcp_id = -1;
            std::string pathToken;

            std::istringstream ss(line);
            std::string token;
            while (ss >> token) {
                if (token.rfind("density=", 0) == 0)
                    density = std::stod(token.substr(8));
                else if (token.rfind("voxelId=", 0) == 0)
                    mrcp_id = std::stoi(token.substr(8));
                else
                    pathToken = token;  // last path token wins
            }

            if (mrcp_id < 0 || pathToken.empty()) continue;

            // Extract basename from potentially absolute path
            std::filesystem::path p(pathToken);
            std::string basename = p.filename().string();
            if (basename.empty()) continue;

            Entry e;
            e.mrcp_id   = mrcp_id;
            e.seq_index = 0;  // assigned below
            e.basename  = basename;
            e.density   = density;
            entries_.push_back(e);
        }

        // Sort by mrcp_id ascending — deterministic ordering
        std::sort(entries_.begin(), entries_.end(),
                  [](const Entry& a, const Entry& b){ return a.mrcp_id < b.mrcp_id; });

        // Assign sequential indices:
        //   mrcp_id == 0  →  seq 0 (external air, always first after sort)
        //   others        →  1, 2, 3, ...
        int next_seq = 0;
        for (auto& e : entries_) {
            e.seq_index = next_seq++;
            mrcp_to_seq_[e.mrcp_id] = e.seq_index;
        }

        if (entries_.empty())
            throw std::runtime_error("MCRPMaterialMap: no entries parsed from " + configPath);

        std::cout << "MCRPMaterialMap: loaded " << entries_.size()
                  << " materials from " << configPath << std::endl;
    }

    // Returns the sequential uint8 index for a given MRCP organ ID.
    // Returns 0 (air background) if the ID is not in the map.
    int getSeqIndex(int mrcp_id) const
    {
        auto it = mrcp_to_seq_.find(mrcp_id);
        if (it == mrcp_to_seq_.end()) {
            std::cerr << "MCRPMaterialMap: unknown MRCP ID " << mrcp_id
                      << ", defaulting to 0 (air)" << std::endl;
            return 0;
        }
        return it->second;
    }

    // Writes the [SECTION MATERIAL FILE LIST] block ready to paste into a .in file.
    // Format per line:
    //   material/<phantomName>/<basename> density=<val> voxelId=<seq>
    void writeMCGPUSectionFile(const std::string& outPath,
                               const std::string& phantomName) const
    {
        std::ofstream out(outPath);
        if (!out.is_open())
            throw std::runtime_error("MCRPMaterialMap: cannot write " + outPath);

        out << "#[SECTION MATERIAL FILE LIST v.2020-03-03]\n";
        for (const auto& e : entries_) {
            out << "material/" << phantomName << "/" << e.basename
                << " density=" << std::fixed << std::setprecision(6) << e.density
                << " voxelId=" << e.seq_index << "\n";
        }
        out.close();
        std::cout << "MCRPMaterialMap: section file written to " << outPath << std::endl;
    }

    const std::vector<Entry>& entries() const { return entries_; }

private:
    std::vector<Entry>  entries_;
    std::map<int, int>  mrcp_to_seq_;   // MRCP_ID → sequential index
};
